name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToGitHubPackagesRepository publishAllPublicationsToGitLabRepository
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITLAB_TOKEN: "${{ secrets.GITLAB_TOKEN }}"
