name: Qodona
on: [push]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: "${{ secrets.QODANA_TOKEN }}"
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "${{ runner.temp }}/qodana/results/qodana.sarif.json"
